In [ ]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

from xgboost import XGBRegressor

In [ ]:
connection_string = (
    "mssql+pyodbc://@localhost/mlb?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

engine = create_engine(connection_string)

query = """
select * from mlb.dbo.fact_hitter_pitcher_matchup_model_features
"""

df = pd.read_sql(query, engine)
print(df.shape)
df.head()

(24609, 448)

,gamePk,game_date,season,hitter_id,hitter_name,hitter_position,hitter_team_id,hitter_team_name,pitcher_id,pitcher_name,...,pitcher_avg_chase_rate_last_10,pitcher_avg_zone_rate_last_10,pitcher_avg_velocity_last_10,pitcher_avg_spin_rate_last_10,pitcher_avg_sl_whiff_rate_last_10,pitcher_avg_ff_whiff_rate_last_10,pitcher_prev_whiff_rate,pitcher_prev_csw_rate,pitcher_prev_chase_rate,pitcher_strikeOuts
0,778032,2025-05-06,2025,672695,Geraldo Perdomo,SS,109,Arizona Diamondbacks,656849,David Peterson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
1,777013,2025-07-25,2025,666181,Will Benson,LF,113,Cincinnati Reds,641793,Zack Littell,...,0.282231,0.534879,87.684055,1827.276940,0.078336,0.122787,0.112360,0.235955,0.306122,2
2,776712,2025-08-16,2025,672580,Maikel Garcia,3B,118,Kansas City Royals,680732,Sean Burke,...,0.320924,0.493231,88.397858,2492.036148,0.124928,0.119645,0.102273,0.306818,0.324324,3
3,776152,2025-09-27,2025,669369,Bryce Johnson,CF,135,San Diego Padres,694851,Andrew Hoffmann,...,0.263626,0.448639,90.804374,1635.216126,0.230159,0.117464,0.090909,0.181818,0.181818,0
4,777731,2025-05-28,2025,671289,Tyler Freeman,RF,115,Colorado Rockies,571510,Matthew Boyd,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8

In [ ]:
# to a list of all the columns in a txt file 
with open("columns.txt", "w") as f:
    for col in df.columns:
        f.write(col + "\n")

In [12]:
# define features and targets
# X = features & y = target

target = "pitcher_strikeOuts"

drop_cols = [
    "gamePk",
    "game_date",
    "hitter_name",
    "pitcher_name",
    "hitter_position",
    "hitter_team_name",
    "pitcher_team_name"
]


leakage_cols = [
    "hitter_strikeOuts",
    "pitches_seen_vs_pitcher",
    "swings_vs_pitcher",
    "whiffs_vs_pitcher",
    "called_strikes_vs_pitcher",
    "matchup_whiff_rate",
    "matchup_called_strike_rate",
    "matchup_csw_rate"
]

X = df.drop(columns=drop_cols + leakage_cols + [target])
y = df[target]

print(X.shape)
print(y.shape)

(24609, 432)
(24609,)

In [13]:
important_features = [
        # ===== Pitcher form =====
    "pitcher_avg_k_last_3",
    "pitcher_avg_k_last_5",
    "pitcher_avg_k_last_10",
    "pitcher_prev_k",
        # ===== Opportunity =====
    "pitcher_avg_bf_last_3",
    "pitcher_avg_ip_last_3",
    "pitcher_avg_pitches_last_3",
    "pitcher_avg_outs_last_3",
        # ===== Skill =====
    "pitcher_avg_whiff_rate_last_3",
    "pitcher_avg_whiff_rate_last_5",
    "pitcher_avg_whiff_rate_last_10",
    "pitcher_avg_velocity_last_3",
    "pitcher_avg_spin_rate_last_3",
    "pitcher_avg_putaway_rate_last_3",
        # ===== Context =====
    "pitcher_throws",
    "hitter_stand"
    ""
]

X = X[important_features]
print(X.shape)

(24609, 16)

In [14]:
train_df = df[df["season"] == 2025]
test_df = df[df["season"] == 2026]

X_train = train_df[important_features]
y_train = train_df[target]

X_test = test_df[important_features]
y_test = test_df[target]

print(X_train.shape, X_test.shape)

(20905, 16) (3704, 16)

In [15]:
X_train = pd.get_dummies(X_train, columns=["pitcher_throws", "hitter_stand"], drop_first=True)
X_test  = pd.get_dummies(X_test,  columns=["pitcher_throws", "hitter_stand"], drop_first=True)

# Align columns (VERY IMPORTANT)
X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

In [16]:
model = XGBRegressor(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [17]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[5.292556  5.2666264 5.8953276 5.077209  3.779169  6.0871763 1.5693507
 5.6125827 1.2733473 5.622337 ]

In [ ]:

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 1.7902448177337646
RMSE: 2.2149879906460113

In [ ]:
results = test_df.copy()

results["predicted_strikeouts"] = y_pred

results[[
    "pitcher_name",
    "pitcher_team_name",   
    "pitcher_strikeOuts",
    "predicted_strikeouts"
]].head(20)

,pitcher_name,pitcher_team_name,pitcher_strikeOuts,predicted_strikeouts
18,Chad Patrick,Milwaukee Brewers,4,5.292556
30,Brandon Williamson,Cincinnati Reds,4,5.266626
40,Connelly Early,Boston Red Sox,4,5.895328
46,Will Warren,New York Yankees,6,5.077209
47,Freddy Peralta,New York Mets,7,3.779169
49,Gavin Williams,Cleveland Guardians,10,6.087176
51,Anthony Bender,Miami Marlins,1,1.569351
60,Albert Suárez,Baltimore Orioles,2,5.612583
62,Jordan Romano,Los Angeles Angels,2,1.273347
79,Logan Gilbert,Seattle Mariners,7,5.622337
86,Sean Burke,Chicago White Sox,7,4.674760
96,Kyle Freeland,Colorado Rockies,6,4.548625
97,Brayan Bello,Boston Red Sox,2,4.927520
98,Emmet Sheehan,Los Angeles Dodgers,6,5.325478
108,Luis Castillo,Seattle Mariners,7,5.211785
112,Tatsuya Imai,Houston Astros,9,4.806517
114,Kevin Gausman,Toronto Blue Jays,11,4.998434
118,Matt Gage,San Francisco Giants,2,1.065060
122,Andrew Abbott,Cincinnati Reds,2,4.385712
126,Jeffrey Springs,Athletics,2,4.909687

In [ ]:
pitcher_preds = results.groupby(
    ["gamePk", "pitcher_name", "pitcher_team_name"]  # 👈 added
).agg(
    actual_K=("pitcher_strikeOuts", "first"),
    predicted_K=("predicted_strikeouts", "mean")
).reset_index()

pitcher_preds.head(50)

    gamePk        pitcher_name     pitcher_team_name  actual_K  predicted_K
0   822753           Brad Lord  Washington Nationals         2     3.091576
1   822753          Cole Henry  Washington Nationals         3     1.457871
2   822753    Michael McGreevy   St. Louis Cardinals         1     4.682560
3   822753       Miles Mikolas  Washington Nationals         3     4.596870
4   822753           PJ Poulin  Washington Nationals         0     1.473283
5   822753       Riley O'Brien   St. Louis Cardinals         0     1.216035
6   822754        Cade Cavalli  Washington Nationals         3     3.977152
7   822754          Cole Henry  Washington Nationals         1     1.537610
8   822754      George Soriano   St. Louis Cardinals         3     1.237577
9   822754  Matthew Liberatore   St. Louis Cardinals         6     4.854645
10  822754           PJ Poulin  Washington Nationals         2     1.242055
11  822754       Riley O'Brien   St. Louis Cardinals         2     1.205937
12  822755      Andre Pallante   St. Louis Cardinals         2     4.589794
13  822755         JoJo Romero   St. Louis Cardinals         0     1.822101
14  822755       Justin Bruihl   St. Louis Cardinals         0     1.128746
15  822755       Ken Waldichuk  Washington Nationals         2     2.437611
16  822755         Ryne Stanek   St. Louis Cardinals         1     1.321433
17  822755        Zack Littell  Washington Nationals         6     4.776204
18  822756          Alex Vesia   Los Angeles Dodgers         0     1.260124
19  822756        Cionel Pérez  Washington Nationals         0     1.187811
20  822756      Clayton Beeter  Washington Nationals         2     1.225295
21  822756      Foster Griffin  Washington Nationals         6     5.552550
22  822756           PJ Poulin  Washington Nationals         2     1.179706
23  822756         Roki Sasaki   Los Angeles Dodgers         5     4.966525
24  822756        Tanner Scott   Los Angeles Dodgers         1     1.211483
25  822757           Brad Lord  Washington Nationals         0     3.512645
26  822757   Edgardo Henriquez   Los Angeles Dodgers         0     1.430518
27  822757          Jake Irvin  Washington Nationals         4     5.230607
28  822757       Tyler Glasnow   Los Angeles Dodgers         9     6.318049
29  822758      Andre Granillo  Washington Nationals         0     1.792191
30  822758       Emmet Sheehan   Los Angeles Dodgers         2     6.067328
31  822758       Miles Mikolas  Washington Nationals         4     4.264236
32  822831          Edwin Díaz   Los Angeles Dodgers         3     1.279353
33  822831       Kevin Gausman     Toronto Blue Jays         5     5.317423
34  822831       Louis Varland     Toronto Blue Jays         2     1.337927
35  822831      Mason Fluharty     Toronto Blue Jays         2     1.205968
36  822831  Yoshinobu Yamamoto   Los Angeles Dodgers         6     4.835498
37  822832   Edgardo Henriquez   Los Angeles Dodgers         2     1.275102
38  822832        Joe Mantiply     Toronto Blue Jays         1     2.627263
39  822832    Justin Wrobleski   Los Angeles Dodgers         2     3.709164
40  822832        Max Scherzer     Toronto Blue Jays         2     4.755214
41  822832         Tommy Nance     Toronto Blue Jays         3     1.246028
42  822832          Will Klein   Los Angeles Dodgers         2     1.266236
43  822833       Ben Casparius   Los Angeles Dodgers         0     1.292024
44  822833         Dylan Cease     Toronto Blue Jays         8     6.043287
45  822833         Jack Dreyer   Los Angeles Dodgers         0     1.107455
46  822834      Brendon Little     Toronto Blue Jays         1     1.809949
47  822834     Chase Dollander      Colorado Rockies         5     4.647189
48  822834       Louis Varland     Toronto Blue Jays         3     1.163309
49  822834       Spencer Miles     Toronto Blue Jays         2     1.207037